/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class jni_ImagePort */

#ifndef _Included_jni_ImagePort
#define _Included_jni_ImagePort
struct Hjava_lang_Object;

#pragma pack(4)

typedef struct Classjni_ImagePort {
    long width;
    long height;
    struct HArrayOfInt *pixels;
    struct HArrayOfArray *cgm;
    struct Hjava_lang_Object *o;
} Classjni_ImagePort;
HandleTo(jni_ImagePort);

#pragma pack()

#ifdef __cplusplus
extern "C" {
#endif
struct Hjava_lang_String;
extern long jni_ImagePort_read(struct Hjni_ImagePort *,struct Hjava_lang_String *);
extern long jni_ImagePort_write(struct Hjni_ImagePort *,struct Hjava_lang_String *);
#ifdef __cplusplus
}
#endif
#endif
